name: 'Terraform FMT (shift left: code formating check)'

on:
  push:
    branches:
      - 'development'
      - 'task/**'
      - 'issue/**'
    paths:
      - 'infrastructure/**.tf'
      - 'infrastructure/modules/application/**.tf'
      - 'infrastructure/app-level/**.tf'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Verify Terraform version
        run: terraform --version
      
      - name: Terraform Formatting
        run: terraform fmt -recursive -diff -check -list=true .